esphome:
  includes:
    - src/eggslice.h
    - src/eggslice.cpp
    - src/eggslice_GSLC.h
    - src/eggslice_GSLC.cpp
    - src/FreeSans14pt7b.h
    - src/NotoMono24pt7b.h
    - src/NotoSansBold14pt7b.h
    - src/dosis_book12pt7b.h
    - src/dosis_book16pt7b.h
    - src/pijlGlyph.h
    - src/wifinone.c
    - src/wifi33.c
    - src/wifi66.c
    - src/wifi100.c
    - src/soft_egg80.c
    - src/medium_egg80.c
    - src/hard_egg80.c
  libraries:
    - Wire
    - SPI
    - FS
    - SPIFFS
    - Preferences
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit GFX Library
    - adafruit/Adafruit ILI9341
    - thingpulse/ThingPulse XPT2046 Touch
    - https://github.com/Amanoo/EggCooker_TFT_eSPI.git
    - https://github.com/Amanoo/EggCooker_GUIslice.git
  name: "eggcooker"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  
web_server:
  port: 80

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-eggcooker"
    password: ""

captive_portal:

# Define the custom component
custom_component:
  - lambda: |-
      auto my_custom = new EggCooker(id(secs),id(state));
      App.register_component(my_custom);
      return {my_custom};


sensor:
  - platform: template
    name: "Egg Cooker Time"
    device_class: duration
    id: secs
    unit_of_measurement: s
    accuracy_decimals: 0
    icon: "mdi:timer-sand"

text_sensor:
  - platform: template
    name: "Egg Cooker State"
    id: state
    icon: "mdi:timer-cog-outline"
