esphome:
  includes:
    - src/eggslice.h
    - src/eggslice.cpp
    - src/eggslice_GSLC.h
    - src/eggslice_GSLC.cpp
    - graphics/FreeSans14pt7b.h
    - graphics/NotoMono24pt7b.h
    - graphics/NotoSansBold14pt7b.h
    - graphics/dosis_book12pt7b.h
    - graphics/dosis_book16pt7b.h
    - graphics/pijlGlyph.h
    - graphics/wifinone.c
    - graphics/wifi33.c
    - graphics/wifi66.c
    - graphics/wifi100.c
    - graphics/soft_egg80.c
    - graphics/medium_egg80.c
    - graphics/hard_egg80.c
  libraries:
    - Wire
    - SPI
    - FS
    - SPIFFS
    - Preferences
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit GFX Library
    - adafruit/Adafruit ILI9341
    - thingpulse/ThingPulse XPT2046 Touch
    - https://github.com/Amanoo/EggCooker_TFT_eSPI.git
    - https://github.com/Amanoo/EggCooker_GUIslice.git
  name: "eggcooker"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-eggcooker"
    password: ""

captive_portal:

# Define the custom component
custom_component:
  - id: cooker
    lambda: |-
      auto my_custom = new EggCooker(id(secs),id(state),id(size),id(hardness));
      App.register_component(my_custom);
      return {my_custom};


sensor:
  - platform: template
    name: "Egg Cooker Time"
    device_class: duration
    id: secs
    unit_of_measurement: s
    accuracy_decimals: 0
    icon: "mdi:timer-sand"

switch:
  - platform: template
    name: "Egg Cooker State"
    id: state
    restore_mode: ALWAYS_OFF
    icon: "mdi:timer-cog-outline"
    turn_on_action:
      - lambda: |-
          timerOn();
    turn_off_action:
      - lambda: |-
          timerOff();

select:
  - platform: template
    name: "Egg size"
    id: size
    optimistic: true
    restore_value: true
    options:
      - S
      - M
      - L
      - XL
  - platform: template
    name: "Egg hardness"
    id: hardness
    optimistic: true
    icon: "mdi:egg-outline"
    restore_value: true
    options:
      - soft
      - medium
      - hard
